/*
 * @(#)PkgSeguridadIntranetException.java  2008/09/09 16:44:59
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:ud65laYiUo7mfT3l55T7QW>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

/**
 * Exception thrown when the execution of a procedure fails.
 */
public class PkgSeguridadIntranetException extends java.lang.Exception
{
    private static final long serialVersionUID = 1L;

    /**
     * Create a new PkgSeguridadIntranetException with supplied procedure name and cause.
     */
    public PkgSeguridadIntranetException(String procedure, Throwable cause)
    {
        super("Execution of procedure "+procedure+" failed", cause);
    }
}
