/*
 * @(#)SpSegBuscarGraUrlCaller.java  2008/09/09 16:44:58
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:DweqJozn0lkV+HkEocPMfH>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.util.ArrayList;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import javax.sql.DataSource;

/**
 * Implements a caller of the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_BUSCAR_GRA_URL" database procedure.
 */
public class SpSegBuscarGraUrlCaller extends ProcedureCaller
{
    /**
     * Executes the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_BUSCAR_GRA_URL" database procedure.
     *
     * O_COD_ERROR        NUMBER             Output
     * O_PAGE_ID          NUMBER             Output
     * I_USER             VARCHAR2(4000)     Input
     * I_URL              VARCHAR2(4000)     Input
     */
    public static SpSegBuscarGraUrlResult execute(DataSource dataSource, String iUser, String iUrl)
        throws java.sql.SQLException
    {
        SpSegBuscarGraUrlResult result = new SpSegBuscarGraUrlResult();
        Connection conn = dataSource.getConnection();
        try
        {
            ArrayList resultSets = new ArrayList();
            CallableStatement call = conn.prepareCall("{call SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_BUSCAR_GRA_URL(?,?,?,?)}");
            try
            {
                call.registerOutParameter(1, Types.NUMERIC);
                call.registerOutParameter(2, Types.NUMERIC);
                call.setString(3, iUser);
                call.setString(4, iUrl);
                executeCall(call, resultSets);
                result.setOCodError(call.getBigDecimal(1));
                result.setOPageId(call.getBigDecimal(2));
            }
            finally
            {
                call.close();
            }
        }
        finally
        {
            conn.close();
        }
        return result;
    }
}
