/*
 * @(#)SpSegBuscarIdCaller.java  2008/09/09 16:44:58
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:dzqEWKUF5dCGMc1ikYqBq+>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import javax.sql.DataSource;

/**
 * Implements a caller of the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_BUSCAR_ID" database procedure.
 */
public class SpSegBuscarIdCaller extends ProcedureCaller
{
    /**
     * Executes the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_BUSCAR_ID" database procedure.
     *
     * O_COD_ERROR        NUMBER             Output
     * O_STRID            VARCHAR2(4000)     Output
     * I_APP_ID           NUMBER             Input
     * I_USER             VARCHAR2(4000)     Input
     */
    public static SpSegBuscarIdResult execute(DataSource dataSource, BigDecimal iAppId, String iUser)
        throws java.sql.SQLException
    {
        SpSegBuscarIdResult result = new SpSegBuscarIdResult();
        Connection conn = dataSource.getConnection();
        try
        {
            ArrayList resultSets = new ArrayList();
            CallableStatement call = conn.prepareCall("{call SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_BUSCAR_ID(?,?,?,?)}");
            try
            {
                call.registerOutParameter(1, Types.NUMERIC);
                call.registerOutParameter(2, Types.VARCHAR);
                call.setBigDecimal(3, iAppId);
                call.setString(4, iUser);
                executeCall(call, resultSets);
                result.setOCodError(call.getBigDecimal(1));
                result.setOStrid(call.getString(2));
            }
            finally
            {
                call.close();
            }
        }
        finally
        {
            conn.close();
        }
        return result;
    }
}
