/*
 * @(#)SpSegBuscarGraUrlResult.java  2008/09/09 16:44:58
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:z4ENt45AwiuGwYAcNBKVxY>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SEGURIDAD_INTRANET.SP_SEG_BUSCAR_GRA_URL".
 */
public class SpSegBuscarGraUrlResult implements java.io.Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myOCodError;
    private BigDecimal myOPageId;

    /**
     * Create a new SpSegBuscarGraUrlResult.
     */
    public SpSegBuscarGraUrlResult() {}

    /**
     * Gets the OCodError value of this SpSegBuscarGraUrlResult.
     */
    public BigDecimal getOCodError()
    {
        return myOCodError;
    }

    /**
     * Sets the OCodError value of this SpSegBuscarGraUrlResult.
     */
    public void setOCodError(BigDecimal value)
    {
        myOCodError = value;
    }

    /**
     * Gets the OPageId value of this SpSegBuscarGraUrlResult.
     */
    public BigDecimal getOPageId()
    {
        return myOPageId;
    }

    /**
     * Sets the OPageId value of this SpSegBuscarGraUrlResult.
     */
    public void setOPageId(BigDecimal value)
    {
        myOPageId = value;
    }
}
