/*
 * @(#)SpSegInsertarPagResult.java  2008/09/09 16:44:59
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:DzE0c1FbhUO8HEE2aB8vwW>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.math.BigDecimal;

/**
 * Output parameters of procedure "PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_PAG".
 */
public class SpSegInsertarPagResult implements java.io.Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myOCodError;
    private BigDecimal myOIdPage;

    /**
     * Create a new SpSegInsertarPagResult.
     */
    public SpSegInsertarPagResult() {}

    /**
     * Gets the OCodError value of this SpSegInsertarPagResult.
     */
    public BigDecimal getOCodError()
    {
        return myOCodError;
    }

    /**
     * Sets the OCodError value of this SpSegInsertarPagResult.
     */
    public void setOCodError(BigDecimal value)
    {
        myOCodError = value;
    }

    /**
     * Gets the OIdPage value of this SpSegInsertarPagResult.
     */
    public BigDecimal getOIdPage()
    {
        return myOIdPage;
    }

    /**
     * Sets the OIdPage value of this SpSegInsertarPagResult.
     */
    public void setOIdPage(BigDecimal value)
    {
        myOIdPage = value;
    }
}
