/*
 * @(#)SpSegInsertarIdCaller.java  2008/09/09 16:44:58
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:KRkT5WuI3HYVzZt7duUbH0>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Date;
import java.sql.Types;
import javax.sql.DataSource;

/**
 * Implements a caller of the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_ID" database procedure.
 */
public class SpSegInsertarIdCaller extends ProcedureCaller
{
    /**
     * Executes the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_ID" database procedure.
     *
     * O_COD_ERROR        NUMBER             Output
     * I_GRANT_ID         NUMBER             Input
     * I_ROL              NUMBER             Input
     * I_PAGINA           NUMBER             Input
     * I_URL              VARCHAR2(1000)     Input
     * I_FECHA_INICIO     DATE               Input
     * I_FECHA_TERMINO    DATE               Input
     */
    public static SpSegInsertarIdResult execute(DataSource dataSource, BigDecimal iGrantId, BigDecimal iRol, BigDecimal iPagina, String iUrl, Date iFechaInicio, Date iFechaTermino)
        throws java.sql.SQLException
    {
        SpSegInsertarIdResult result = new SpSegInsertarIdResult();
        Connection conn = dataSource.getConnection();
        try
        {
            ArrayList resultSets = new ArrayList();
            CallableStatement call = conn.prepareCall("{call SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_ID(?,?,?,?,?,?,?)}");
            try
            {
                call.registerOutParameter(1, Types.NUMERIC);
                call.setBigDecimal(2, iGrantId);
                call.setBigDecimal(3, iRol);
                call.setBigDecimal(4, iPagina);
                call.setString(5, iUrl);
                call.setDate(6, iFechaInicio);
                call.setDate(7, iFechaTermino);
                executeCall(call, resultSets);
                result.setOCodError(call.getBigDecimal(1));
            }
            finally
            {
                call.close();
            }
        }
        finally
        {
            conn.close();
        }
        return result;
    }
}
