/*
 * @(#)SpSegInsertarPagCaller.java  2008/09/09 16:44:59
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:PP12F8g-9tHVtyd12RGq92>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import javax.sql.DataSource;

/**
 * Implements a caller of the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_PAG" database procedure.
 */
public class SpSegInsertarPagCaller extends ProcedureCaller
{
    /**
     * Executes the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_PAG" database procedure.
     *
     * O_COD_ERROR        NUMBER             Output
     * O_ID_PAGE          NUMBER             Output
     * I_NOMBRE_PAG       VARCHAR2(4000)     Input
     */
    public static SpSegInsertarPagResult execute(DataSource dataSource, String iNombrePag, BigDecimal iIdMod,BigDecimal iIdApp)
        throws java.sql.SQLException
    {
        SpSegInsertarPagResult result = new SpSegInsertarPagResult();
        Connection conn = dataSource.getConnection();
        try
        {
            ArrayList resultSets = new ArrayList();
            CallableStatement call = conn.prepareCall("{call SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_PAG(?,?,?,?,?)}");
            try
            {
                call.registerOutParameter(1, Types.NUMERIC);
                call.registerOutParameter(2, Types.NUMERIC);
                call.setString(3, iNombrePag);
                call.setBigDecimal(4,iIdMod);
                call.setBigDecimal(5,iIdApp);
                executeCall(call, resultSets);
                result.setOCodError(call.getBigDecimal(1));
                result.setOIdPage(call.getBigDecimal(2));
            }
            finally
            {
                call.close();
            }
        }
        finally
        {
            conn.close();
        }
        return result;
    }
}
