/*
 * @(#)SpSegInsertarGraCaller.java  2008/09/09 16:44:58
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:I19R+hRSa9jEJe6dKWYHEQ>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.util.ArrayList;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import javax.sql.DataSource;

/**
 * Implements a caller of the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_GRA" database procedure.
 */
public class SpSegInsertarGraCaller extends ProcedureCaller
{
    /**
     * Executes the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_GRA" database procedure.
     *
     * O_COD_ERROR        NUMBER             Output
     * I_NOMBRE_GRANT     VARCHAR2(4000)     Input
     */
    public static SpSegInsertarGraResult execute(DataSource dataSource, String iNombreGrant)
        throws java.sql.SQLException
    {
        SpSegInsertarGraResult result = new SpSegInsertarGraResult();
        Connection conn = dataSource.getConnection();
        try
        {
            ArrayList resultSets = new ArrayList();
            CallableStatement call = conn.prepareCall("{call SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_INSERTAR_GRA(?,?)}");
            try
            {
                call.registerOutParameter(1, Types.NUMERIC);
                call.setString(2, iNombreGrant);
                executeCall(call, resultSets);
                result.setOCodError(call.getBigDecimal(1));
            }
            finally
            {
                call.close();
            }
        }
        finally
        {
            conn.close();
        }
        return result;
    }
}
