/*
 * @(#)SpSegModificarGraCaller.java  2008/09/09 16:44:59
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:1HusBcR4ZDnHK6yI6xU2bc>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import javax.sql.DataSource;

/**
 * Implements a caller of the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_MODIFICAR_GRA" database procedure.
 */
public class SpSegModificarGraCaller extends ProcedureCaller
{
    /**
     * Executes the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_MODIFICAR_GRA" database procedure.
     *
     * O_COD_ERROR        NUMBER             Output
     * I_GRANT            NUMBER             Input
     * I_NOMBRE_GRANT     VARCHAR2(4000)     Input
     * I_GRANT_ESTADO     VARCHAR2(4000)     Input
     */
    public static SpSegModificarGraResult execute(DataSource dataSource, BigDecimal iGrant, String iNombreGrant, String iGrantEstado)
        throws java.sql.SQLException
    {
        SpSegModificarGraResult result = new SpSegModificarGraResult();
        Connection conn = dataSource.getConnection();
        try
        {
            ArrayList resultSets = new ArrayList();
            CallableStatement call = conn.prepareCall("{call SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_MODIFICAR_GRA(?,?,?,?)}");
            try
            {
                call.registerOutParameter(1, Types.NUMERIC);
                call.setBigDecimal(2, iGrant);
                call.setString(3, iNombreGrant);
                call.setString(4, iGrantEstado);
                executeCall(call, resultSets);
                result.setOCodError(call.getBigDecimal(1));
            }
            finally
            {
                call.close();
            }
        }
        finally
        {
            conn.close();
        }
        return result;
    }
}
