/*
 * @(#)SpSegModificarRolCaller.java  2008/09/09 16:44:59
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.195.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:yeP-31yMDfDWnuDECR0Bgs>>.
 */

package cl.tesoreria.seguridad.profile.ejb.pkgseguridadintranet;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import javax.sql.DataSource;

/**
 * Implements a caller of the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_MODIFICAR_ROL" database procedure.
 */
public class SpSegModificarRolCaller extends ProcedureCaller
{
    /**
     * Executes the "SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_MODIFICAR_ROL" database procedure.
     *
     * O_COD_ERROR        NUMBER             Output
     * I_ROL              NUMBER             Input
     * I_NOMBRE_ROL       VARCHAR2(4000)     Input
     * I_ROL_TIPO         VARCHAR2(4000)     Input
     * I_ROL_JERARQ       NUMBER             Input
     * I_ROL_ESTADO       VARCHAR2(4000)     Input
     * I_APL_ID           NUMBER             Input
     */
    public static SpSegModificarRolResult execute(DataSource dataSource, BigDecimal iRol, String iNombreRol, String iRolTipo, BigDecimal iRolJerarq, String iRolEstado, BigDecimal iAplId)
        throws java.sql.SQLException
    {
        SpSegModificarRolResult result = new SpSegModificarRolResult();
        Connection conn = dataSource.getConnection();
        try
        {
            ArrayList resultSets = new ArrayList();
            CallableStatement call = conn.prepareCall("{call SEGURIDAD2.PKG_SEGURIDAD_INTRANET.SP_SEG_MODIFICAR_ROL(?,?,?,?,?,?,?)}");
            try
            {
                call.registerOutParameter(1, Types.NUMERIC);
                call.setBigDecimal(2, iRol);
                call.setString(3, iNombreRol);
                call.setString(4, iRolTipo);
                call.setBigDecimal(5, iRolJerarq);
                call.setString(6, iRolEstado);
                call.setBigDecimal(7, iAplId);
                executeCall(call, resultSets);
                result.setOCodError(call.getBigDecimal(1));
            }
            finally
            {
                call.close();
            }
        }
        finally
        {
            conn.close();
        }
        return result;
    }
}
