//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 02:22:45 PM CLT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://tesoreria.cl/seguridad/profile", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cl.tesoreria.seguridad.profile;
