//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.16 at 02:22:45 PM CLT 
//


package cl.tesoreria.seguridad.profile;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.io.Serializable;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="user" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechaCreacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fechaMod" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rut" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="dv" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nombres" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="apePaterno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="apeMaterno" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="codUbicacion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="tesoreria" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="rutTesoreria" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="dvTesoreria" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="depto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="seccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="funcion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="anexo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="estado" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "user"
})
@XmlRootElement(name = "users")
public class Users implements Serializable{

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@XmlElement(required = true)
    protected List<Users.User> user;

    public void setUser(List<Users.User> user) {
		this.user = user;
	}


	/**
     * Gets the value of the user property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the user property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUser().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Users.User }
     * 
     * 
     */
    public List<Users.User> getUser() {
        if (user == null) {
            user = new ArrayList<Users.User>();
        }
        return this.user;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fechaCreacion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fechaMod" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rut" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="dv" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nombres" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="apePaterno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="apeMaterno" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="codUbicacion" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="tesoreria" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="rutTesoreria" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="dvTesoreria" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="depto" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="seccion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cargo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="funcion" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="anexo" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="estado" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "userId",
        "userName",
        "fechaCreacion",
        "fechaMod",
        "password",
        "rut",
        "dv",
        "nombres",
        "apePaterno",
        "apeMaterno",
        "codUbicacion",
        "tesoreria",
        "rutTesoreria",
        "dvTesoreria",
        "depto",
        "seccion",
        "cargo",
        "funcion",
        "anexo",
        "estado",
        "email"
    })
    public static class User implements Serializable{

        /**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		@XmlElement(required = true)
        protected BigDecimal userId;
        @XmlElement(required = true)
        protected String userName;
        @XmlElement(required = true)
        protected String fechaCreacion;
        @XmlElement(required = true)
        protected String fechaMod;
        @XmlElement(required = true, nillable = true)
        protected String password;
        @XmlElement(required = true, nillable = true)
        protected BigDecimal rut;
        @XmlElement(required = true, nillable = true)
        protected String dv;
        @XmlElement(required = true, nillable = true)
        protected String nombres;
        @XmlElement(required = true, nillable = true)
        protected String apePaterno;
        @XmlElement(required = true, nillable = true)
        protected String apeMaterno;
        @XmlElement(required = true, nillable = true)
        protected BigDecimal codUbicacion;
        @XmlElement(required = true, nillable = true)
        protected String tesoreria;
        @XmlElement(required = true, nillable = true)
        protected BigDecimal rutTesoreria;
        @XmlElement(required = true, nillable = true)
        protected String dvTesoreria;
        @XmlElement(required = true, nillable = true)
        protected String depto;
        @XmlElement(required = true, nillable = true)
        protected String seccion;
        @XmlElement(required = true, nillable = true)
        protected String cargo;
        @XmlElement(required = true, nillable = true)
        protected String funcion;
        @XmlElement(required = true, nillable = true)
        protected String anexo;
        @XmlElement(required = true, nillable = true)
        protected String estado;
        @XmlElement(required = true, nillable = true)
        protected String email;

        /**
         * Gets the value of the userId property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUserId() {
            return userId;
        }

        /**
         * Sets the value of the userId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUserId(BigDecimal value) {
            this.userId = value;
        }

        /**
         * Gets the value of the userName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserName() {
            return userName;
        }

        /**
         * Sets the value of the userName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserName(String value) {
            this.userName = value;
        }

        /**
         * Gets the value of the fechaCreacion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaCreacion() {
            return fechaCreacion;
        }

        /**
         * Sets the value of the fechaCreacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaCreacion(String value) {
            this.fechaCreacion = value;
        }

        /**
         * Gets the value of the fechaMod property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFechaMod() {
            return fechaMod;
        }

        /**
         * Sets the value of the fechaMod property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFechaMod(String value) {
            this.fechaMod = value;
        }

        /**
         * Gets the value of the password property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassword() {
            return password;
        }

        /**
         * Sets the value of the password property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassword(String value) {
            this.password = value;
        }

        /**
         * Gets the value of the rut property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRut() {
            return rut;
        }

        /**
         * Sets the value of the rut property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRut(BigDecimal value) {
            this.rut = value;
        }

        /**
         * Gets the value of the dv property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDv() {
            return dv;
        }

        /**
         * Sets the value of the dv property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDv(String value) {
            this.dv = value;
        }

        /**
         * Gets the value of the nombres property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNombres() {
            return nombres;
        }

        /**
         * Sets the value of the nombres property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNombres(String value) {
            this.nombres = value;
        }

        /**
         * Gets the value of the apePaterno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApePaterno() {
            return apePaterno;
        }

        /**
         * Sets the value of the apePaterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApePaterno(String value) {
            this.apePaterno = value;
        }

        /**
         * Gets the value of the apeMaterno property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApeMaterno() {
            return apeMaterno;
        }

        /**
         * Sets the value of the apeMaterno property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApeMaterno(String value) {
            this.apeMaterno = value;
        }

        /**
         * Gets the value of the codUbicacion property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCodUbicacion() {
            return codUbicacion;
        }

        /**
         * Sets the value of the codUbicacion property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCodUbicacion(BigDecimal value) {
            this.codUbicacion = value;
        }

        /**
         * Gets the value of the tesoreria property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTesoreria() {
            return tesoreria;
        }

        /**
         * Sets the value of the tesoreria property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTesoreria(String value) {
            this.tesoreria = value;
        }

        /**
         * Gets the value of the rutTesoreria property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getRutTesoreria() {
            return rutTesoreria;
        }

        /**
         * Sets the value of the rutTesoreria property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setRutTesoreria(BigDecimal value) {
            this.rutTesoreria = value;
        }

        /**
         * Gets the value of the dvTesoreria property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDvTesoreria() {
            return dvTesoreria;
        }

        /**
         * Sets the value of the dvTesoreria property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDvTesoreria(String value) {
            this.dvTesoreria = value;
        }

        /**
         * Gets the value of the depto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepto() {
            return depto;
        }

        /**
         * Sets the value of the depto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepto(String value) {
            this.depto = value;
        }

        /**
         * Gets the value of the seccion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSeccion() {
            return seccion;
        }

        /**
         * Sets the value of the seccion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSeccion(String value) {
            this.seccion = value;
        }

        /**
         * Gets the value of the cargo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCargo() {
            return cargo;
        }

        /**
         * Sets the value of the cargo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCargo(String value) {
            this.cargo = value;
        }

        /**
         * Gets the value of the funcion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFuncion() {
            return funcion;
        }

        /**
         * Sets the value of the funcion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFuncion(String value) {
            this.funcion = value;
        }

        /**
         * Gets the value of the anexo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnexo() {
            return anexo;
        }

        /**
         * Sets the value of the anexo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnexo(String value) {
            this.anexo = value;
        }

        /**
         * Gets the value of the estado property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEstado() {
            return estado;
        }

        /**
         * Sets the value of the estado property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEstado(String value) {
            this.estado = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEmail() {
            return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEmail(String value) {
            this.email = value;
        }

    }

}
